spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:arenacode}
    username: ${POSTGRES_USER:arenacode}
    password: ${POSTGRES_PASSWORD:local-dev-password}
  flyway:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:arenacode}
    user: ${POSTGRES_USER:arenacode}
    password: ${POSTGRES_PASSWORD:local-dev-password}

app:
  jwt:
    secret: "test-secret-key-that-is-at-least-32-bytes-long"
    issuer: "arenacode-test"
    access-token-ttl: PT15M
